// This file has been generated by the Python script generate_cpymodule.py. Do not edit it.
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <numpy/arrayobject.h>
#include "pypelib.h"
PyObject * setup_wrapper(PyObject *self, PyObject *args) {
      int toret = 0;
      PyObject *name = NULL, *config_block = NULL, *data_block = NULL;
      if (!PyArg_ParseTuple(args, "OOO", &name, &config_block, &data_block)) goto except;
      const char * name_str = PyUnicode_AsUTF8(name);
      toret = setup(name_str, (DataBlock *) config_block, (DataBlock *) data_block);
      //if (toret != 0) _PyErr_FormatFromCause(PyExc_RuntimeError,"Exception (signal %d) in function setup of module [%S].", toret, name);
      if ((toret != 0) && (!PyErr_Occurred()))
        PyErr_Format(PyExc_RuntimeError,"Exception (signal %d) in function setup of module [%S].", toret, name);
      goto finally;
    except:
      toret = -1;
    finally:
      if (toret == 0) Py_RETURN_NONE;
      return NULL;
    }

PyObject * execute_wrapper(PyObject *self, PyObject *args) {
      int toret = 0;
      PyObject *name = NULL, *config_block = NULL, *data_block = NULL;
      if (!PyArg_ParseTuple(args, "OOO", &name, &config_block, &data_block)) goto except;
      const char * name_str = PyUnicode_AsUTF8(name);
      toret = execute(name_str, (DataBlock *) config_block, (DataBlock *) data_block);
      //if (toret != 0) _PyErr_FormatFromCause(PyExc_RuntimeError,"Exception (signal %d) in function execute of module [%S].", toret, name);
      if ((toret != 0) && (!PyErr_Occurred()))
        PyErr_Format(PyExc_RuntimeError,"Exception (signal %d) in function execute of module [%S].", toret, name);
      goto finally;
    except:
      toret = -1;
    finally:
      if (toret == 0) Py_RETURN_NONE;
      return NULL;
    }

PyObject * cleanup_wrapper(PyObject *self, PyObject *args) {
      int toret = 0;
      PyObject *name = NULL, *config_block = NULL, *data_block = NULL;
      if (!PyArg_ParseTuple(args, "OOO", &name, &config_block, &data_block)) goto except;
      const char * name_str = PyUnicode_AsUTF8(name);
      toret = cleanup(name_str, (DataBlock *) config_block, (DataBlock *) data_block);
      //if (toret != 0) _PyErr_FormatFromCause(PyExc_RuntimeError,"Exception (signal %d) in function cleanup of module [%S].", toret, name);
      if ((toret != 0) && (!PyErr_Occurred()))
        PyErr_Format(PyExc_RuntimeError,"Exception (signal %d) in function cleanup of module [%S].", toret, name);
      goto finally;
    except:
      toret = -1;
    finally:
      if (toret == 0) Py_RETURN_NONE;
      return NULL;
    }

static PyMethodDef pypemethods[] = {
  {"setup", setup_wrapper, METH_VARARGS, "Setup module."},
  {"execute", execute_wrapper, METH_VARARGS, "Execute module."},
  {"cleanup", cleanup_wrapper, METH_VARARGS, "Cleanup module."},
  {NULL, NULL, 0, NULL}        /* Sentinel */
};

static PyModuleDef pypemodule = {
  PyModuleDef_HEAD_INIT,
  .m_name = "module",
  .m_doc = "Template C++ module",
  .m_size = -1,
  .m_methods = pypemethods,
};

PyMODINIT_FUNC
PyInit_module(void)
{
  import_array();
  if (import_datablock()<0) return NULL;
  return PyModule_Create(&pypemodule);
}
