name: pypescript-docs

channels:
- defaults
- conda-forge

dependencies:
- python=3.8
- pip
- pyyaml
- numpy
- scipy
- mpi4py
- matplotlib
- sphinx
- sphinx_rtd_theme
- pip:
  - git+https://github.com/adematti/pypescript
