# This file has been generated by the Python script pypescript/libutils/generate_section_names.py
# Edit the root file pypescript/section_names.yaml if necessary.
common = 'common'
mpi = 'mpi'
nocopy = ['common', 'mpi']