# This file has been generated by the Python script /home/adematti/anaconda3/envs/cosmopipe/lib/python3.8/site-packages/pypescript/setuppype/generate_section_names.py
# Edit the root file section_names.yaml if necessary.
common = 'common'
mpi = 'mpi'
nocopy = ['common', 'mpi']